spring:
  application:
    name: pado-server
  profiles:
    active: local
jwt:
  secret: ${JWT_SECRET}
app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}
---
spring:
  config:
    activate:
      on-profile: ci  

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
    redis:
      url: ${SPRING_REDIS_URL}

  cloud:
    vault:
      uri: http://localhost:8200
      token: root
      scheme: http
      authentication: TOKEN
      connection-timeout: 5000
      read-timeout: 15000
      config:
        lifecycle:
          enabled: false

      kv:
        enabled: true
        backend: secret
        default-context: application
        profile-separator: '-'
---
server:
  forward-headers-strategy: framework
spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:mysql://${PADO_MYSQL_DEV_URL}:3306/pado
    username: ${PADO_ID}
    password: ${PADO_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    mongodb:
      uri: mongodb://${PADO_ID}:${PADO_PW}@${PADO_MONGO_DEV_URL}:27017/pado
    redis:
      url: redis://${PADO_ID}:${PADO_PW}@${PADO_REDIS_DEV_URL}:6379/0
  
  cloud:
    vault:
      uri: http://${PADO_VAULT_DEV_URL}:8200
      token: ${VAULT_DEV_TOKEN}
      scheme: http
      authentication: TOKEN
      connection-timeout: 5000
      read-timeout: 15000
      config:
        lifecycle:
          enabled: false

      kv:
        enabled: true
        backend: secret
        default-context: application
        profile-separator: '-'

---
spring:
  config:
    activate:
      on-profile: local

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:mysql://localhost:3306/pado
    username: ${PADO_ID}
    password: ${PADO_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  data:
    mongodb:
      uri: mongodb://${PADO_ID}:${PADO_PW}@localhost:27017/pado
    redis:
      url: redis://${PADO_ID}:${PADO_PW}@localhost:6379/0
  
  cloud:
    vault:
      uri: http://localhost:8200
      token: ${VAULT_DEV_TOKEN}
      scheme: http
      authentication: TOKEN
      connection-timeout: 5000
      read-timeout: 15000
      config:
        lifecycle:
          enabled: false

      kv:
        enabled: true
        backend: secret
        default-context: application
        profile-separator: '-'
