name: Dev CI Pipeline

on:
  pull_request:
    branches: [ "dev" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Start Redis
      uses: supercharge/redis-github-action@1.4.0
      with:
        redis-version: '6'
    
    - name: Run Tests and Build (in api-server)
      working-directory: api-server
      env:
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        REDIS_HOST: localhost
        REDIS_PORT: 6379
        APP_CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:5173"
      run: ./gradlew clean test build -Dspring.profiles.active=ci --info --stacktrace
    