name: Dev CI Pipeline

on:
  pull_request:
    branches: [ "dev" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      # MySQL
      SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/testdb
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: test
      # Redis
      SPRING_REDIS_URL: redis://test:test@localhost:6379/0

      # MongoDB
      SPRING_DATA_MONGODB_URI: mongodb://test:test@127.0.0.1:27017/testdb?authSource=admin

      # Vault (dev)

      VAULT_URI: http://127.0.0.1:8200
      VAULT_ROLE_ID: "test-role-id"
      VAULT_SECRET_ID: "test-secret-id"
      
      JWT_SECRET: test-secret

      PADO_RABBITMQ_HOST: 127.0.0.1
      RABBITMQ_USERNAME: test
      RABBITMQ_PASSWORD: testpw
      RABBITMQ_VHOST: "/"   # spring.rabbitmq.virtual-host 설정에 매핑됨
      
    services:
      mysql:
        image: mysql:8.0
        ports: ["3306:3306"]
        env:
          MYSQL_ROOT_PASSWORD: test
          MYSQL_DATABASE: testdb
          MYSQL_USER: test
          MYSQL_PASSWORD: test
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD || exit 1"
          --health-interval=10s --health-timeout=5s --health-retries=10

      redis:
        image: redis:7
        ports: ["6379:6379"]
        # 비번이 필요하면 아래처럼:
        # options: >-
        #   --cmd "redis-server --requirepass redispw"
        options: >-
          --health-cmd="redis-cli ping || exit 1"
          --health-interval=10s --health-timeout=3s --health-retries=10

      mongo:
        image: mongo:7
        ports: ["27017:27017"]
        env:
          MONGO_INITDB_ROOT_USERNAME: test
          MONGO_INITDB_ROOT_PASSWORD: test
          MONGO_INITDB_DATABASE: testdb
        options: >-
          --health-cmd="mongosh --quiet --eval 'db.runCommand({ ping: 1 })' || exit 1"
          --health-interval=10s --health-timeout=5s --health-retries=10

      vault:
        image: hashicorp/vault:1.15
        ports: ["8200:8200"]
        env:
          VAULT_DEV_ROOT_TOKEN_ID: root
          VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
        options: >-
          --cap-add=IPC_LOCK
          --health-cmd="wget -qO- http://127.0.0.1:8200/v1/sys/health || exit 1"
          --health-interval=10s --health-timeout=5s --health-retries=20

      rabbitmq:
        image: rabbitmq:3.13-management
        ports:
          - "5672:5672"   # AMQP
          - "15672:15672" # 관리 콘솔
        env:
          RABBITMQ_DEFAULT_USER: test
          RABBITMQ_DEFAULT_PASS: testpw
          RABBITMQ_DEFAULT_VHOST: "/"
        options: >-
          --health-cmd="rabbitmq-diagnostics -q ping"
          --health-interval=10s --health-timeout=5s --health-retries=10
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Wait for services (extra safety)
      run: |
        set -e
        # MySQL
        for i in {1..30}; do
          nc -z 127.0.0.1 3306 && echo "MySQL up" && break || sleep 2
        done
        # Redis
        for i in {1..30}; do
          nc -z 127.0.0.1 6379 && echo "Redis up" && break || sleep 2
        done
        # Mongo
        for i in {1..30}; do
          nc -z 127.0.0.1 27017 && echo "Mongo up" && break || sleep 2
        done
        # Vault
        for i in {1..30}; do
          curl -s $VAULT_URI/v1/sys/health >/dev/null && echo "Vault up" && break || sleep 2
        done
        # RabbitMQ
        for i in {1..30}; do
          nc -z 127.0.0.1 5672 && echo "RabbitMQ up" && break || sleep 2
        done
    
    - name: Setup Vault App-Role for CI
      run: |
        # Vault CLI 설치
        curl -fsSL https://releases.hashicorp.com/vault/1.15.0/vault_1.15.0_linux_amd64.zip -o vault.zip
        unzip vault.zip
        sudo mv vault /usr/local/bin/
          
        export VAULT_ADDR=http://127.0.0.1:8200
        export VAULT_TOKEN=root
          
        # App-Role 설정
        vault auth enable approle || true
        vault policy write ci-policy - <<EOF
        path "secret/*" { 
          capabilities = ["create", "read", "update", "delete", "list"] 
        }
        EOF
        vault write auth/approle/role/ci-role token_policies="ci-policy" token_ttl=1h
          
        # 실제 값으로 환경변수 덮어쓰기
        echo "VAULT_ROLE_ID=$(vault read -field=role_id auth/approle/role/ci-role/role-id)" >> $GITHUB_ENV
        echo "VAULT_SECRET_ID=$(vault write -field=secret_id -f auth/approle/role/ci-role/secret-id)" >> $GITHUB_ENV
  

    - name: Run Tests and Build (in api-server)
      working-directory: api-server
      run: ./gradlew clean test build -Dspring.profiles.active=ci --info --stacktrace
        
